export const LOCATIONS = {
    'hanoi': 'Hà Nội',
    'tphochiminh': 'Tp. Hồ Chí Minh',
    'hochiminh': 'Tp. Hồ Chí Minh',
    'danang': 'Đà Nẵng',
    'angiang': 'An Giang',
    'bacgiang': 'Bắc Giang',
    'backan': 'Bắc Kạn',
    'baclieu': 'Bạc Liêu',
    'bacninh': 'Bắc Ninh',
    'bentre': 'Bến Tre',
    'binhdinh': 'Bình Định',
    'binhduong': 'Bình Dương',
    'binhphuoc': 'Bình Phước',
    'binhthuan': 'Bình Thuận',
    'camau': 'Cà Mau',
    'cantho': 'Cần Thơ',
    'caobang': 'Cao Bằng',
    'daklak': 'Đắk Lắk',
    'daknong': 'Đắk Nông',
    'dienbien': 'Điện Biên',
    'dongnai': 'Đồng Nai',
    'dongthap': 'Đồng Tháp',
    'gialai': 'Gia Lai',
    'hagiang': 'Hà Giang',
    'hanam': 'Hà Nam',
    'hatinh': 'Hà Tĩnh',
    'haiduong': 'Hải Dương',
    'haiphong': 'Hải Phòng',
    'haugiang': 'Hậu Giang',
    'hoabinh': 'Hòa Bình',
    'hungyen': 'Hưng Yên',
    'khanhhoa': 'Khánh Hòa',
    'kiengiang': 'Kiên Giang',
    'kontum': 'Kon Tum',
    'laichau': 'Lai Châu',
    'lamdong': 'Lâm Đồng',
    'langson': 'Lạng Sơn',
    'laocai': 'Lào Cai',
    'longan': 'Long An',
    'namdinh': 'Nam Định',
    'nghean': 'Nghệ An',
    'ninhbinh': 'Ninh Bình',
    'ninhthuan': 'Ninh Thuận',
    'phutho': 'Phú Thọ',
    'phuyen': 'Phú Yên',
    'quangbinh': 'Quảng Bình',
    'quangnam': 'Quảng Nam',
    'quangngai': 'Quảng Ngãi',
    'quangninh': 'Quảng Ninh',
    'quangtri': 'Quảng Trị',
    'soctrang': 'Sóc Trăng',
    'sonla': 'Sơn La',
    'tayninh': 'Tây Ninh',
    'thaibinh': 'Thái Bình',
    'thainguyen': 'Thái Nguyên',
    'thanhhoa': 'Thanh Hóa',
    'thuathienhue': 'Thừa Thiên Huế',
    'hue': 'Huế',
    'tiengiang': 'Tiền Giang',
    'travinh': 'Trà Vinh',
    'tuyenquang': 'Tuyên Quang',
    'vinhlong': 'Vĩnh Long',
    'vinhphuc': 'Vĩnh Phúc',
    'vungtau': 'Vũng Tàu',
    'bariavungtau': 'Bà Rịa Vũng Tàu',
    'yenbai': 'Yên Bái',
    'truongsa': 'Quần Đảo Trường Sa',
    'hoangsa': 'Quần Đảo Hoàng Sa',
    'dacnong': 'Đắk Nông'
};
